### PR TITLE
Fix shebang mapping and nil index

### PR DESCRIPTION
**Pull request by luukvbaal**
Getting 

    Vim(lua):E5108: Error executing lua ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:183: attempt to index upvalue 'custom_map' (a nil value)

with no custom mappings defined in `setup()`.

### CODE REVIEW

**Comment by b0o** [comment]
I'm having this same issue, can confirm this PR fixes it.

**Comment by b0o** [comment]
Actually it fixes it but only incidentally, there's a mistake:

```lua
        if custom and custom_map.shebang then
```

should be

```lua
        if custom_map and custom_map.shebang then
```

It "fixed" the error for me because `custom` doesn't exist either, but the real variable name should be `custom_map`.

**Comment by luukvbaal** [comment]
Right, fixed the typo, whoops. Feel free to close if #53 is a better fix.

**Comment by luukvbaal** [comment]
Fix default shebang mappings as described in #53 in a more concise way. Feel free to use whichever you prefer.

**Pull request closed without merging**
