### PR TITLE
improve shebang check

### PR DESCRIPTION
**Pull request by uga-rosa**

### CODE REVIEW

**Comment by uga-rosa** [comment]
I also added a feature that I thought would be nice to have.

**Comment by gegoune** [comment]
@uga-rosa Do you mind if I ask why closed that PR? Was there something wrong with it?

**Comment by uga-rosa** [comment]
It seems that you don't want to merge, but I think you should apply the contents of the improve shenang check.

**Comment by nathom** [comment]
I just hadn't taken a look at your PR yet. It looks good!

**Comment by nathom** [comment]
Can you reopen the pull request?

**Pull request closed without merging**
