### PR TITLE
improve shebang check

### PR DESCRIPTION
**Pull request by uga-rosa**
#18

### CODE REVIEW

**Comment by uga-rosa** [comment]
This is not directly related, but please put stylua.toml. I usually write with two space indentations and it's a pain to fix.

**Comment by nathom** [comment]
@uga-rosa I added the `stylus.toml`.

**Comment by fitrh** [comment]
@uga-rosa did you merge it into the `dev` branch on purpose ?

**Comment by uga-rosa** [comment]
@fitrh I've been told this before.
https://github.com/nathom/filetype.nvim/pull/15#issuecomment-932382298

**Pull request merged**
