### PR TITLE
Add markdownlintrc and gitconfig filetype

### PR DESCRIPTION
**Pull request by younger-1**

### CODE REVIEW

**Comment by younger-1** [comment]
After some consideration, I think the filetype added my commit is not so useful for most people.

May it will be nice to config filetype for personal use like:
```lua
require("filetype").override({
  literal = {
    [".markdownlintrc"] = "jsonc",
    ["gitconfig"] = "gitconfig",
  }
})
```

Is it possible to achieve? 🐤

**Comment by nathom** [comment]
Yes, it is possible if you use the `dev` branch. Check out the README on that branch; there are instructions.

**Comment by disrupted** [comment]
`gitconfig` seems like a useful addition for everyone imo

**Comment by nathom** [comment]
I added `gitconfig`.

**Comment by younger-1** [comment]
> Yes, it is possible if you use the `dev` branch. Check out the README on that branch; there are instructions.

Thank you so much!

**Comment by nathom** [comment]
The setup function has been merged into `main`.

**Pull request closed without merging**
