### PR TITLE
Eliminate contamination of namespace and improve overall

### PR DESCRIPTION
**Pull request by uga-rosa**

### CODE REVIEW

**Comment by nathom** [comment]
Nice! Can you set the requested merge branch to `dev` though?

**Comment by nathom** [comment]
Also, can you note down the changes you made? It's not clear from the diff due to file renaming.

**Comment by uga-rosa** [comment]
I have to work, so updates will have to wait a bit.

**Comment by uga-rosa** [comment]
I've separated the commits so you can see the changes in this.

**Comment by nathom** [comment]
Looks good, thanks.

**Comment by uga-rosa** [comment]
Sheban's support is temporary and simple, so I will pr again when it improves.

**Pull request merged**
